class ItemTag:
    WEAPON_AMMUNITION = "weapon_ammunition"
    WEAPON_FINESSE = "weapon_finesse"
    WEAPON_HEAVY = "weapon_heavy"
    WEAPON_LIGHT = "weapon_light"
    WEAPON_LOADING = "weapon_loading"
    WEAPON_RANGE = "weapon_range"
    WEAPON_REACH = "weapon_reach"
    WEAPON_SPECIAL = "weapon_special"
    WEAPON_THROWN = "weapon_thrown"
    WEAPON_TWO_HANDED = "weapon_two_handed"
    WEAPON_VERSATILE = "weapon_versatile"
    MARTIAL_WEAPON = "martial_weapon"
    SIMPLE_WEAPON = "simple_weapon"
    MELEE_WEAPON = "melee_weapon"
    RANGED_WEAPON = "ranged_weapon"
    ARMOR = "armor"